name: Deploy to Netlify

on:
  push:
    branches:
      - feature/practice-one
  pull_request:
    branches:
      - feature/practice-one

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to project directory
        run: cd practice-one

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.3.1"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=./dist
